logger: 
  default: error
  logs:
    py: info
    custom_components.pyscript: info
    custom_components.tapo.coordinators: critical
    custom_components.xiaomi_miot: critical
    androidtv: critical
    miio.miioprotocol: critical
    pychromecast.socket_client: critical
    homeassistant.helpers.entity_registry: fatal # removed when fixed
    
  filters:
    homeassistant:
      - "Error doing job: Future exception was never retrieved" # Tado
      - "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))" # Tado
    custom_components.pyscript:
      - "Unloaded"
    custom_components.pyscript.global_ctx:
      - "Loaded"
      - "Reloaded"
    custom_components.hacs:
      - "https://api.github.com/rate_limit"
    homeassistant.components: 
      - "io.robbie.HomeAssistant"
      - "update_available"
    homeassistant.components.openweathermap: 
      - "timeouted"
    homeassistant.components.hassio:
      - "/addons"
      - "stat"
    homeassistant.components.google_assistant.http:
      - "404"
      - "500"
    homeassistant.helpers.entity:
      - "Remote end closed connection without response"
    homeassistant.util.logging:
      - "HomeAssistant NOT_RUNNING"
    aiohttp.server: 
      - "Error handling request"
    habluetooth.scanner:
      - "org.bluez.Error.InProgress"
    pyvesync.helpers:
      - "No response"
    root:
      - "BEGIN:VEVENT" #caldav
      - "Ical data was modified to avoid compatibility issues" # caldav

logbook:  
  exclude:
    domains:
      - sensor
    entity_globs: 
      - "sensor.*"
      - "*.*browser_mod*"

system_log:
  max_entries: 3