logger: 
  default: error
  logs:
    py: info
    custom_components.pyscript: info
    custom_components.tapo.coordinators: critical
    custom_components.xiaomi_miot: critical
    androidtv: critical
    miio.miioprotocol: critical
    pychromecast.socket_client: critical
  filters:
    homeassistant:
      - "Error doing job: Future exception was never retrieved" # Tado
      - "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))" # Tado
    custom_components.pyscript:
      - "Unloaded"
    custom_components.pyscript.global_ctx:
      - "Loaded"
      - "Reloaded"
    custom_components.hacs:
      - "https://api.github.com/rate_limit"
    homeassistant.components.openweathermap.weather_update_coordinator: 
      - "timeouted"
    homeassistant.components.hassio.handler:
      - "stat"
    homeassistant.components.google_assistant.http:
      - "404"
      - "500"
    homeassistant.components.websocket_api.http.connection: 
      - "io.robbie.HomeAssistant"
    homeassistant.config_entries: 
      - "tado"
    homeassistant.util.logging:
      - "HomeAssistant NOT_RUNNING"
    aiohttp.server: 
      - "Error handling request"
    root:
      - "VEVENT"
      - "ical"
      - "caldav"

logbook: 
  exclude:
    entity_globs: 
      - "*.*browser_mod*"

system_log:
  max_entries: 5